plugins {
    id 'com.android.application'
    id 'com.chaquo.python'
}
android {
    namespace 'ir.paraday.dndbot'
    compileSdk 34
    defaultConfig {
        applicationId 'ir.paraday.dndbot'
        minSdk 24
        targetSdk 33
        versionCode 45
        versionName "2.43"
        ndk { abiFilters 'arm64-v8a', 'armeabi-v7a', 'x86_64' }
        python {
            version '3.10'
            pip {
                install "flask>=3.0"
                install "requests>=2.31"
            }
        }
    }
    packagingOptions { jniLibs { useLegacyPackaging true } }
    buildTypes { release { minifyEnabled false } }
}
