plugins {
    id 'com.android.application'
    id 'com.chaquo.python'
}
android {
    namespace 'ir.paraday.dndbot'
    compileSdk 34
    defaultConfig {
        applicationId 'ir.paraday.dndbot'
        minSdk 24
        targetSdk 33
        versionCode 10
        versionName '2.6'
        ndk { abiFilters 'arm64-v8a', 'armeabi-v7a', 'x86_64' }
        python { version '3.10' }
    }
    // باینری cloudflared به‌صورت libcloudflared.so در jniLibs است؛ باید فیزیکی extract شود تا قابل اجرا باشد
    packagingOptions { jniLibs { useLegacyPackaging = true } }
    buildTypes { release { minifyEnabled false } }
}
